"use client";

import { useEffect, useState } from "react";
import { Activity, BarChart3, BriefcaseBusiness, ShieldAlert } from "lucide-react";
import { Card } from "@/components/ui";
import { ConsolePage } from "@/components/console-page";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "";
type Overview = { verification: { total: number; completed: number; pending: number; completion_rate: number | null }; risk: { low: number; review: number; high: number; average_score: number | null }; cases: { total: number; by_status: Record<string, number>; high_risk: number }; modules: { ocr: { by_status: Record<string, number>; average_confidence: number | null }; validation: { by_status: Record<string, number> }; tampering: { by_status: Record<string, number>; finding_severity: Record<string, number> }; face: { by_outcome: Record<string, number>; quality_failures: number } }; period: { start: string; end: string; timezone: string }; demo: boolean };

export default function AnalyticsPage() { const [days, setDays] = useState("30"); const [data, setData] = useState<Overview | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const load = async () => { setState("loading"); try { const response = await fetch(`${API_URL}/api/v1/analytics/overview?days=${days}`, { credentials: "include" }); if (!response.ok) throw new Error(); setData(await response.json() as Overview); setState("ready"); } catch { setState("error"); } };
  useEffect(() => { void load(); }, [days]); // eslint-disable-line react-hooks/exhaustive-deps
  return <ConsolePage title="TrustID Analytics" description="Operational metrics derived from persisted TrustID records, not fictional government statistics."><Card><div className="analytics-toolbar"><label>Date range<select value={days} onChange={(event) => setDays(event.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></label><span className="timezone-note">All reporting periods use UTC.</span></div></Card>{state === "loading" && <Card><p className="upload-status" role="status">Loading persisted analytics...</p></Card>}{state === "error" && <Card><div className="upload-error" role="alert"><strong>Analytics unavailable</strong><span>Check your authorization or try again.</span></div></Card>}{state === "ready" && data && <><div className="analytics-demo-banner"><strong>{data.demo ? "DEMO / SIMULATED" : "PERSISTED OPERATIONAL DATA"}</strong><span>Metrics count database records. Repeated analysis runs are not counted as new verifications.</span></div><div className="analytics-metric-grid"><Metric icon={<BarChart3 size={20} />} label="Total verifications" value={data.verification.total} /><Metric icon={<Activity size={20} />} label="Completed analyses" value={data.verification.completed} /><Metric icon={<ShieldAlert size={20} />} label="High risk" value={data.risk.high} /><Metric icon={<BriefcaseBusiness size={20} />} label="Total cases" value={data.cases.total} /></div><div className="analytics-grid"><Card><h2>Risk distribution</h2><p className="chart-summary">Latest persisted assessment per verification: {data.risk.low} low, {data.risk.review} review, {data.risk.high} high. Average score: {data.risk.average_score ?? "Unavailable"}.</p><Bars values={[["LOW", data.risk.low], ["REVIEW", data.risk.review], ["HIGH", data.risk.high]]} /></Card><Card><h2>Case status</h2><p className="chart-summary">{data.cases.total ? `${data.cases.total} persisted cases, including ${data.cases.high_risk} linked to high-risk assessments.` : "No data available for this period."}</p><Bars values={Object.entries(data.cases.by_status)} /></Card></div><Card><h2>Module health</h2><div className="module-health-grid"><Health title="OCR" values={data.modules.ocr.by_status} note={data.modules.ocr.average_confidence == null ? "Confidence unavailable" : `Average confidence ${Math.round(data.modules.ocr.average_confidence * 100)}%`} /><Health title="Validation" values={data.modules.validation.by_status} note="Structured rule outcomes" /><Health title="Tampering" values={data.modules.tampering.by_status} note={`Finding severity: ${JSON.stringify(data.modules.tampering.finding_severity)}`} /><Health title="Face comparison" values={data.modules.face.by_outcome} note={`${data.modules.face.quality_failures} quality-related outcomes`} /></div></Card></>}</ConsolePage>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <Card><div className="analytics-metric"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div></Card>; }
function Bars({ values }: { values: [string, number][] }) { const max = Math.max(...values.map(([, value]) => value), 1); return <div className="analytics-bars" aria-label="Accessible metric bar summary">{values.length ? values.map(([label, value]) => <div key={label}><div><strong>{label.replaceAll("_", " ")}</strong><span>{value}</span></div><div className="bar-track"><div className="bar-fill" style={{ width: `${(value / max) * 100}%` }} /></div></div>) : <p className="placeholder-note">No data available for this period.</p>}</div>; }
function Health({ title, values, note }: { title: string; values: Record<string, number>; note: string }) { return <div className="health-card"><strong>{title}</strong>{Object.entries(values).length ? Object.entries(values).map(([key, value]) => <span key={key}>{key}: {value}</span>) : <span>Unavailable</span>}<small>{note}</small></div>; }
