import { AlertTriangle, ArrowRight, BarChart3, CheckCircle2, ClipboardCheck, Database, FileCheck2, FileSearch, Fingerprint, LockKeyhole, Network, ScanLine, Server, ShieldCheck, UserCheck } from "lucide-react";
import type { ReactNode } from "react";
import { Card, Divider, SectionHeader } from "./ui";
import { PublicFooter, PublicHeader } from "./layouts";
import { DemoModeBadge, DocumentStatus, EvidenceBadge, FaceMatchStatus, RiskBadge, RiskScore, TamperingStatus, VerificationStatus } from "./status";
import { EvidenceCard, EvidenceList, FindingExplanation } from "./evidence";

export const featureData = [
  { icon: ScanLine, title: "OCR extraction", text: "Extract structured fields from supported identity and travel documents so officers can review the information in a consistent format." },
  { icon: FileCheck2, title: "Document validation", text: "Check required fields, formats, expiry, consistency, and rules—with authorized external sources only when integrated." },
  { icon: FileSearch, title: "Tampering analysis", text: "Surface indicators of possible photo replacement, text manipulation, stamp forgery, and metadata anomalies." },
  { icon: Fingerprint, title: "Face verification", text: "Compare a presented face with a document portrait when the required inputs are available, without inventing missing signals." },
  { icon: BarChart3, title: "Explainable risk assessment", text: "Combine verification signals into a risk level with reasons, evidence, and a recommended action—not a black-box score." },
  { icon: ClipboardCheck, title: "Investigation and audit trail", text: "Preserve an evidence-oriented record of analysis and officer decisions for future review and investigation support." },
];

const lifecycle = ["Select document", "Upload or capture", "Quality check", "OCR extraction", "Document validation", "Tampering analysis", "Face verification when available", "Risk assessment", "Evidence review", "Officer decision"];

export function PublicPage({ children }: { children: ReactNode }) { return <><PublicHeader /><main>{children}</main><PublicFooter /></>; }

export function Hero() { return <section className="marketing-hero"><div className="hero-copy"><span className="eyebrow">AI-POWERED IDENTITY & DOCUMENT SECURITY PLATFORM</span><h1>Verify Identity.<br /><em>Detect Fraud.</em><br />Protect Every Checkpoint.</h1><p>TrustID is an AI-assisted screening platform that helps authorized personnel analyze identity and travel documents, detect potential tampering, verify available identity signals, assess risk, and understand the evidence behind each result.</p><div className="hero-actions"><a className="button button-primary" href="/login">Start Verification <ArrowRight size={16} /></a><a className="text-link" href="/platform">Explore Platform <ArrowRight size={15} /></a></div><p className="hero-note"><ShieldCheck size={15} /> Decision support for authorized personnel · Not an automatic legal determination</p></div><VerificationConsoleVisual /></section>; }

export function VerificationConsoleVisual() { return <div className="hero-visual"><div className="visual-top"><div><span className="visual-kicker">VERIFICATION PREVIEW</span><strong>Evidence-oriented result</strong></div><DemoModeBadge /></div><div className="visual-document"><div className="visual-doc-photo"><UserCheck size={30} /><small>DEMO DOCUMENT</small></div><div className="visual-doc-fields"><span>Passport document</span><strong>Identity fields extracted</strong><div><i /> Name · Passport no. · Expiry</div><div><i /> Nationality · Date of birth</div></div></div><div className="visual-signals"><span><CheckCircle2 size={14} /> OCR ready</span><span><CheckCircle2 size={14} /> Validation clear</span><span><AlertTriangle size={14} /> Review signals</span></div><div className="visual-result"><div><span className="label">RISK ASSESSMENT</span><strong>08 <small>/100</small></strong></div><div><VerificationStatus verified /><p>Reasons and evidence available to review</p></div></div></div>; }

export function CredibilityStrip() { return <section className="credibility-strip"><div><strong>AI-assisted screening</strong><span>Structured analysis signals</span></div><div><strong>Evidence-first analysis</strong><span>Understand what happened and why</span></div><div><strong>Explainable risk assessment</strong><span>Reasons, confidence, and action</span></div><div><strong>Officer decision support</strong><span>Authorized personnel stay in control</span></div></section>; }

export function ProblemSection() { return <section className="marketing-section problem-section"><SectionHeader eyebrow="The screening challenge" title="Manual screening gets harder as complexity and volume increase." description="At a busy checkpoint, officers may need to review inconsistent documents, altered photographs, modified dates of birth, suspicious visa stamps, expired records, and identity impersonation signals—often under time pressure." /><div className="problem-grid">{["Fake passports and visas", "Altered photographs and text", "Tampered stamps and seals", "Identity impersonation", "Expired or blacklisted documents", "High passenger volume"].map((item) => <div className="problem-item" key={item}><AlertTriangle size={17} />{item}</div>)}</div><p className="section-footnote">TrustID is designed to make review more consistent and evidence-oriented. It does not replace authorized judgment or guarantee fraud detection.</p></section>; }

export function SolutionSection() { return <section className="marketing-section solution-section"><div className="solution-heading"><SectionHeader eyebrow="The TrustID approach" title="One workflow. Multiple signals. An evidence-oriented result." description="TrustID hides technical complexity without hiding the evidence. Each stage contributes a distinct signal to help officers understand the result." /><a className="text-link" href="/how-it-works">See how it works <ArrowRight size={15} /></a></div><div className="workflow-line">{["Document", "OCR", "Validation", "Tampering", "Face", "Risk", "Evidence", "Decision"].map((step, index) => <div className="workflow-step" key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong>{index < 7 && <ArrowRight size={15} />}</div>)}</div></section>; }

export function HowItWorksSection() { return <section className="marketing-section alt-section"><SectionHeader eyebrow="How it works" title="A clear lifecycle from document to decision." description="Inputs and available signals vary by verification. Face comparison and external source checks are only used when their required inputs or authorized integrations exist." /><div className="lifecycle-grid">{lifecycle.map((step, index) => <div className="lifecycle-step" key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong></div>)}</div></section>; }

export function FeaturesSection() { return <section className="marketing-section"><SectionHeader eyebrow="Core capabilities" title="The signals officers need, in one place." description="Each capability is designed to answer what it does, why it matters, and what evidence can support review—without overclaiming model performance." /><div className="feature-grid">{featureData.map(({ icon: Icon, title, text }) => <Card key={title} className="feature-card"><div className="feature-icon"><Icon size={21} /></div><h3>{title}</h3><p>{text}</p><a href="/platform" aria-label={`Learn more about ${title}`}>Learn more <ArrowRight size={14} /></a></Card>)}</div></section>; }

export function IntelligenceSection() { return <section className="marketing-section intelligence-section"><div><SectionHeader eyebrow="Verification intelligence" title="A recommendation should never be the end of the story." description="TrustID is built around a simple principle: hide technical complexity, never hide evidence. Findings should explain what, why, where, confidence, and recommended action." /><div className="intelligence-points"><span><CheckCircle2 size={17} /> Document status stays separate from risk level</span><span><CheckCircle2 size={17} /> NO_MATCH is not the same as COULD_NOT_VERIFY</span><span><CheckCircle2 size={17} /> Analysis failure is not a fraud determination</span></div></div><div className="intelligence-card"><RiskScore score={8} level="LOW" reasons={["Document fields are internally consistent", "No suspicious signals in this demo preview"]} /><div className="result-row"><DocumentStatus status="VALID" /><FaceMatchStatus status="MATCH" /><TamperingStatus clear /></div><EvidenceBadge>Evidence available for review</EvidenceBadge></div></section>; }

export function SecuritySection() { return <section className="marketing-section security-section"><SectionHeader eyebrow="Security principles" title="Designed for controlled, auditable screening." description="TrustID's foundation prioritizes safe handling and clear accountability without making unsupported certification or security claims." /><div className="security-grid">{[[LockKeyhole, "Controlled access", "Role-aware boundaries can help ensure sensitive workflows are available only to authorized personnel."], [Database, "Safe storage", "Document artifacts use an S3-compatible storage abstraction with future retention controls."], [ClipboardCheck, "Audit trails", "Analysis and officer decisions are designed to leave a reviewable digital trail."], [Network, "Provider-neutral architecture", "AI services stay behind application interfaces so the frontend is not coupled to providers."]].map(([Icon, title, text]) => { const SecurityIcon = Icon as typeof LockKeyhole; return <div className="security-item" key={title as string}><SecurityIcon size={20} /><div><h3>{title as string}</h3><p>{text as string}</p></div></div>; })}</div></section>; }

export function UseCasesSection() { return <section className="marketing-section alt-section"><SectionHeader eyebrow="Operational use cases" title="Built to assist the people responsible for the decision." description="TrustID can support multiple screening contexts while keeping authorized personnel in control of the final decision." /><div className="use-case-grid">{["Border checkpoints", "Immigration screening", "Document verification", "Identity screening", "Investigation support", "Audit and compliance workflows"].map((item) => <Card key={item} className="use-case-card"><ShieldCheck size={19} /><h3>{item}</h3><p>Evidence-oriented screening support for authorized personnel, with simulated integrations clearly identified.</p></Card>)}</div></section>; }

export function TechnologySection() { return <section className="marketing-section technology-section"><div><SectionHeader eyebrow="Technology" title="A modular foundation for responsible scale." description="The technical architecture separates the public experience, verification API, orchestration, AI services, and data systems so future implementations can evolve without rewriting the workflow." /><a className="text-link" href="/technology">Explore technical architecture <ArrowRight size={15} /></a></div><div className="architecture-stack"><div><Server size={17} /> Public Web</div><ArrowRight size={16} /><div><Network size={17} /> Verification API</div><ArrowRight size={16} /><div><ScanLine size={17} /> Service interfaces</div><ArrowRight size={16} /><div><Database size={17} /> PostgreSQL · Redis · Object storage</div></div></section>; }

export function FinalCTA() { return <section className="final-cta"><span className="eyebrow">TRUSTID</span><h2>Make every check clearer, faster, and easier to review.</h2><p>Explore the platform foundation and see how evidence-oriented decision support can fit into authorized screening workflows.</p><div className="hero-actions"><a className="button button-primary" href="/platform">Explore Platform <ArrowRight size={16} /></a><a className="text-link light" href="/about">About TrustID <ArrowRight size={15} /></a></div></section>; }

export function PlatformPageContent() { return <PublicPage><InnerHero eyebrow="Platform" title="A complete screening foundation, designed around evidence." text="TrustID brings document intelligence, identity signals, tampering analysis, risk context, and audit-ready workflow into one modular platform for authorized personnel." /><div className="marketing-section"><div className="feature-grid">{featureData.map(({ icon: Icon, title, text }) => <Card key={title} className="feature-card"><div className="feature-icon"><Icon size={21} /></div><h3>{title}</h3><p>{text}</p></Card>)}</div></div><UseCasesSection /><FinalCTA /></PublicPage>; }
export function HowItWorksPageContent() { return <PublicPage><InnerHero eyebrow="How it works" title="From document selection to an auditable decision." text="The verification lifecycle is explicit, inspectable, and designed to preserve the distinction between system analysis and officer judgment." /><HowItWorksSection /><section className="marketing-section"><div className="semantic-grid">{[["EXPIRED", "Document status", "A document validity result—not a risk level."], ["HIGH RISK", "Risk level", "A risk context—not a processing state."], ["NO_MATCH", "Identity result", "A comparison result—not the same as inability to verify."], ["ANALYSIS FAILED", "Processing outcome", "A failure to complete analysis—not a fraud determination."]].map(([label, title, text]) => <Card key={label}><span className="status-badge status-review">{label}</span><h3>{title}</h3><p>{text}</p></Card>)}</div></section><FinalCTA /></PublicPage>; }
export function TechnologyPageContent() { return <PublicPage><InnerHero eyebrow="Technology" title="Modular by design. Provider-neutral by default." text="TrustID separates the user experience from verification orchestration and AI implementations so future production integrations can be introduced responsibly." /><section className="marketing-section"><div className="architecture-detail"><div className="architecture-stack large"><div><Server size={18} /> Next.js · React · TypeScript</div><ArrowRight size={17} /><div><Network size={18} /> FastAPI verification API</div><ArrowRight size={17} /><div><ScanLine size={18} /> Verification orchestrator and service interfaces</div><ArrowRight size={17} /><div><Database size={18} /> PostgreSQL · Redis · S3-compatible storage</div></div><div className="technology-copy"><h3>What this enables</h3><p>Frontend code never depends directly on an AI provider. OCR, validation, tampering, face, and risk services can have demo implementations first and production implementations later.</p><p>Optional blockchain anchoring may provide tamper-evident audit infrastructure in the future; it is not the core verification mechanism.</p><p>Authorized external verification providers remain explicit integrations, not assumed government connectivity.</p></div></div></section><FinalCTA /></PublicPage>; }
export function SecurityPageContent() { return <PublicPage><InnerHero eyebrow="Security" title="Security principles that support accountable screening." text="TrustID is designed around controlled access, safe handling, minimal sensitive logging, and an evidence-oriented workflow. It does not claim certifications or guaranteed security." /><SecuritySection /><section className="marketing-section"><div className="callout"><ShieldCheck size={22} /><div><h3>Trust is built through clarity</h3><p>Clear labels, explicit demo boundaries, reviewable evidence, and officer-controlled decisions are part of the product&apos;s security posture.</p></div></div></section><FinalCTA /></PublicPage>; }
export function AboutPageContent() { return <PublicPage><InnerHero eyebrow="About TrustID" title="Smart identity verification for clearer decisions." text="TrustID is a prototype platform aligned to Smart India Hackathon problem statement 26188: AI-Based Fake Identity & Document Screening System." /><section className="marketing-section about-grid"><div><SectionHeader eyebrow="Product principle" title="Verify. Detect. Protect." description="Upload a document → TrustID analyzes it → TrustID explains what it found → authorized personnel make the decision." /></div><Card><h3>Product boundary</h3><p>TrustID assists authorized personnel. It is not an autonomous legal decision maker, a criminality classifier, a government database, or a guarantee of fraud detection.</p><Divider /><p className="section-footnote">Organization context: Ministry of Home Affairs · Sashastra Seema Bal, Police II Division · Software · Blockchain & Cybersecurity theme.</p></Card></section><FinalCTA /></PublicPage>; }
export function LoginPlaceholder() { return <PublicPage><section className="login-placeholder"><div className="login-card"><LockKeyhole size={25} /><span className="eyebrow">SECURE CONSOLE ENTRY</span><h1>Sign in to TrustID</h1><p>Authentication is not enabled in this phase. This placeholder reserves the protected entry point for a future secure console implementation.</p><DemoModeBadge /><a className="text-link" href="/">Return to public site <ArrowRight size={15} /></a></div></section></PublicPage>; }

function InnerHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="inner-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></section>; }
