"use client";

import { useEffect, useState } from "react";
import { ArrowRight, BriefcaseBusiness, Search } from "lucide-react";
import { Card } from "@/components/ui";
import { ConsolePage } from "@/components/console-page";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "";
type CaseItem = { id: string; case_number: string; title: string; status: string; priority: string; verification_id: string; updated_at: string };

export default function CasesPage() {
  const [cases, setCases] = useState<CaseItem[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [priority, setPriority] = useState(""); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const load = async () => { setState("loading"); try { const params = new URLSearchParams(); if (search) params.set("search", search); if (status) params.set("status", status); if (priority) params.set("priority", priority); const response = await fetch(`${API_URL}/api/v1/cases?${params}`, { credentials: "include" }); if (!response.ok) throw new Error("Cases could not be loaded."); setCases(await response.json() as CaseItem[]); setState("ready"); } catch { setState("error"); } };
  // The loader is intentionally recreated with the active server-side filters.
  useEffect(() => { void load(); }, [status, priority]); // eslint-disable-line react-hooks/exhaustive-deps
  return <ConsolePage title="Cases & Investigation" description="Manage authorized officer investigations linked to existing verification results."><div className="case-demo-banner"><strong>DEMO / SIMULATED workflow</strong><span>Cases are operational records and do not independently establish fraud, criminality, or legal status.</span></div><Card><div className="case-filters"><label><span>Search case number or title</span><div className="case-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void load(); }} placeholder="TRUST-2026-000001" /></div></label><label><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option>OPEN</option><option>UNDER_REVIEW</option><option>ESCALATED</option><option>RESOLVED</option><option>CLOSED</option></select></label><label><span>Priority</span><select value={priority} onChange={(event) => setPriority(event.target.value)}><option value="">All priorities</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><button type="button" className="button button-secondary" onClick={() => void load()}>Search</button></div></Card><Card><div className="case-table-heading"><div><h2>Investigation cases</h2><p>{state === "ready" ? `${cases.length} case${cases.length === 1 ? "" : "s"} in your authorized view.` : "Loading authorized cases..."}</p></div><BriefcaseBusiness size={24} /></div>{state === "error" && <div className="upload-error" role="alert"><strong>Unable to load cases</strong><span>Check your session or try again.</span></div>}{state === "ready" && cases.length === 0 && <div className="case-empty"><BriefcaseBusiness size={28} /><strong>No cases found</strong><span>Create an investigation case from a completed verification analysis.</span></div>}{state === "ready" && cases.length > 0 && <div className="case-table-wrap"><table className="case-table"><thead><tr><th>Case</th><th>Priority</th><th>Status</th><th>Updated</th><th>Action</th></tr></thead><tbody>{cases.map((item) => <tr key={item.id}><td><strong>{item.case_number}</strong><span>{item.title}</span></td><td><span className={`case-pill priority-${item.priority.toLowerCase()}`}>{item.priority}</span></td><td><span className={`case-pill status-${item.status.toLowerCase()}`}>{item.status.replaceAll("_", " ")}</span></td><td>{new Date(item.updated_at).toLocaleString()}</td><td><a className="button button-secondary button-small" href={`/console/cases/${item.id}`}>Open <ArrowRight size={14} /></a></td></tr>)}</tbody></table></div>}</Card></ConsolePage>;
}
