"use client";

import { ChangeEvent, DragEvent, useState } from "react";
import { CheckCircle2, FileText, IdCard, Plane, ScanLine, UploadCloud, X } from "lucide-react";
import { Card } from "@/components/ui";
import { ConsolePage } from "@/components/console-page";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
const MAX_DOCUMENT_SIZE_BYTES = 10 * 1024 * 1024;
const documentTypes = [["PASSPORT", "Passport", Plane], ["VISA", "Visa", FileText], ["NATIONAL_ID", "National ID", IdCard], ["DRIVING_LICENSE", "Driving License", IdCard], ["PERMIT", "Permit", FileText]] as const;
const accepted = new Map([[".pdf", "application/pdf"], [".jpg", "image/jpeg"], [".jpeg", "image/jpeg"], [".png", "image/png"], [".webp", "image/webp"]]);
const scenarios = [["CLEAN", "Clean document"], ["TEXT_MANIPULATION", "Text manipulation"], ["PHOTO_INCONSISTENCY", "Photo inconsistency"], ["STAMP_ALTERATION", "Visa/stamp alteration"], ["METADATA_ANOMALY", "Metadata anomaly"]] as const;
type OCRResult = { id: string; status: string; raw_text: string; language: string; overall_confidence: number; provider: string; provider_version: string; fields: { name: string; value: string; normalized_value: string; confidence: number; source_text: string; evidence?: { page?: number; line_index?: number } | null }[] };
type TamperingResult = { id: string; status: string; technical_signal_score: number; overall_confidence: number; provider: string; summary: string; findings: { id: string; finding_type: string; severity: string; confidence: number; title: string; description: string; related_ocr_field?: string | null; evidence: { evidence_type: string; page?: number | null; region?: string | null; description: string; technical_signal: string; confidence: number }[] }[] };
type FaceResult = { id: string; status: string; outcome: string; similarity_score?: number | null; confidence?: number | null; provider: string; summary: string; failure_reason?: string | null; document_face_quality: string; presented_face_quality: string; face_count?: number | null; evidence: { name: string; value: string; explanation: string }[] };
type AnalysisResult = { verification_id: string; document_id: string; status: string; modules: { name: string; status: string; summary: string }[]; validation: { status: string; summary: string; findings: { name: string; passed: boolean; severity: string; explanation: string }[] }; risk: { risk_score: number; risk_level: string; recommendation: string; confidence?: number | null; summary: string; factors: { name: string; source_module: string; severity: string; contribution: number; explanation: string }[] } };

function validateFile(file: File): string | null {
  const extension = `.${file.name.split(".").pop()?.toLowerCase() ?? ""}`;
  if (!accepted.has(extension)) return "Unsupported document type. Use PDF, JPG, PNG, or WebP.";
  if (file.type && file.type !== accepted.get(extension)) return "The file type does not match its declared content type.";
  if (!file.size) return "The selected file is empty.";
  if (file.size > MAX_DOCUMENT_SIZE_BYTES) return "The document exceeds the 10 MB maximum size.";
  return null;
}

export default function VerifyPage() {
  const [type, setType] = useState("PASSPORT");
  const [file, setFile] = useState<File | null>(null);
  const [documentId, setDocumentId] = useState<string | null>(null);
  const [verificationId, setVerificationId] = useState<string | null>(null);
  const [state, setState] = useState<"idle" | "validating" | "uploading" | "success" | "error">("idle");
  const [ocrState, setOcrState] = useState<"idle" | "processing" | "complete" | "error">("idle");
  const [tamperingState, setTamperingState] = useState<"idle" | "processing" | "complete" | "error">("idle");
  const [faceState, setFaceState] = useState<"idle" | "preparing" | "comparing" | "complete" | "error">("idle");
  const [presentedFace, setPresentedFace] = useState<File | null>(null);
  const [faceScenario, setFaceScenario] = useState("MATCH");
  const [faceResult, setFaceResult] = useState<FaceResult | null>(null);
  const [analysisState, setAnalysisState] = useState<"idle" | "processing" | "complete" | "error">("idle");
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  const [scenario, setScenario] = useState("CLEAN");
  const [ocrResult, setOcrResult] = useState<OCRResult | null>(null);
  const [tamperingResult, setTamperingResult] = useState<TamperingResult | null>(null);
  const [message, setMessage] = useState("");
  const choose = (candidate: File | undefined) => { if (!candidate) return; const error = validateFile(candidate); setMessage(error ?? ""); setFile(error ? null : candidate); setState(error ? "error" : "validating"); setDocumentId(null); setVerificationId(null); setOcrResult(null); setTamperingResult(null); setFaceResult(null); setAnalysisResult(null); setOcrState("idle"); setTamperingState("idle"); setFaceState("idle"); setAnalysisState("idle"); };
  const onDrop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); choose(event.dataTransfer.files[0]); };
  const onChange = (event: ChangeEvent<HTMLInputElement>) => choose(event.target.files?.[0]);
  const upload = async () => {
    if (!file) return;
    setState("uploading"); setMessage("");
    try {
      const verification = await fetch(`${API_URL}/api/v1/verifications`, { method: "POST", credentials: "include" });
      if (!verification.ok) throw new Error("Unable to start a verification.");
      const { id } = await verification.json() as { id: string };
      const body = new FormData(); body.append("document_type", type); body.append("file", file);
      const response = await fetch(`${API_URL}/api/v1/verifications/${id}/documents`, { method: "POST", credentials: "include", body });
      const data = await response.json().catch(() => ({})) as { detail?: string; id?: string; verification_id?: string };
      if (!response.ok || !data.id || !data.verification_id) throw new Error(data.detail ?? "The document could not be uploaded.");
      setDocumentId(data.id); setVerificationId(data.verification_id); setState("success"); setMessage("Document uploaded successfully. Ready for OCR.");
    } catch (error) { setState("error"); setMessage(error instanceof Error ? error.message : "Upload failed. Try again."); }
  };
  const startOCR = async () => {
    if (!documentId) return;
    setOcrState("processing"); setMessage("");
    try { const response = await fetch(`${API_URL}/api/v1/documents/${documentId}/ocr`, { method: "POST", credentials: "include" }); const data = await response.json().catch(() => ({})) as OCRResult & { detail?: string }; if (!response.ok) throw new Error(data.detail ?? "OCR processing could not be completed."); setOcrResult(data); setOcrState("complete"); }
    catch (error) { setOcrState("error"); setMessage(error instanceof Error ? error.message : "OCR processing could not be completed."); }
  };
  const startTampering = async () => {
    if (!documentId) return;
    setTamperingState("processing"); setMessage("");
    try { const response = await fetch(`${API_URL}/api/v1/documents/${documentId}/tampering`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scenario }) }); const data = await response.json().catch(() => ({})) as TamperingResult & { detail?: string }; if (!response.ok) throw new Error(data.detail ?? "Technical analysis could not be completed."); setTamperingResult(data); setTamperingState("complete"); }
    catch (error) { setTamperingState("error"); setMessage(error instanceof Error ? error.message : "Technical analysis could not be completed."); }
  };
  const startFaceVerification = async () => {
    if (!documentId || !presentedFace) return;
    setFaceState("preparing"); setMessage("");
    try { const body = new FormData(); body.append("image", presentedFace); body.append("scenario", faceScenario); setFaceState("comparing"); const response = await fetch(`${API_URL}/api/v1/documents/${documentId}/face-verification`, { method: "POST", credentials: "include", body }); const data = await response.json().catch(() => ({})) as FaceResult & { detail?: string }; if (!response.ok) throw new Error(data.detail ?? "Face verification could not be completed."); setFaceResult(data); setFaceState("complete"); }
    catch (error) { setFaceState("error"); setMessage(error instanceof Error ? error.message : "Face verification could not be completed."); }
  };
  const startAnalysis = async () => {
    if (!verificationId) return;
    setAnalysisState("processing"); setMessage("");
    try { const response = await fetch(`${API_URL}/api/v1/verifications/${verificationId}/analyze`, { method: "POST", credentials: "include" }); const data = await response.json().catch(() => ({})) as AnalysisResult & { detail?: string }; if (!response.ok) throw new Error(data.detail ?? "Verification analysis could not be completed."); setAnalysisResult(data); setAnalysisState("complete"); }
    catch (error) { setAnalysisState("error"); setMessage(error instanceof Error ? error.message : "Verification analysis could not be completed."); }
  };
  return <ConsolePage title="New Verification" description="Securely ingest a document, extract text, and review technical signals for future validation.">
    <div className="console-demo-banner"><strong>Phase 8 · Face verification foundation</strong><span>Face comparison is photo-based demo analysis. It does not prove identity, authenticity, liveness, or fraud.</span></div>
    <Card><div className="console-card-heading"><div><h2>Step 1 · Document type</h2><p>Select the category that matches the document.</p></div><ScanLine size={24} /></div><div className="document-type-grid">{documentTypes.map(([value, label, Icon]) => <button type="button" className={`document-type-option ${type === value ? "selected" : ""}`} key={value} onClick={() => setType(value)} aria-pressed={type === value}><Icon size={22} /><strong>{label}</strong><span>{type === value ? "Selected" : "Select"}</span></button>)}</div></Card>
    <Card><div className="console-card-heading"><div><h2>Step 2 · Upload document</h2><p>Accepted: PDF, JPG, PNG, WebP · Maximum size: 10 MB</p></div><UploadCloud size={24} /></div><div className="upload-dropzone" onDragOver={(event) => event.preventDefault()} onDrop={onDrop}><UploadCloud size={30} /><strong>Drop a document here</strong><span>or use the accessible file picker below</span><label className="button button-secondary" htmlFor="document-file">Choose file</label><input id="document-file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={onChange} /></div>{file && <div className="selected-file"><FileText size={20} /><div><strong>{file.name}</strong><span>{(file.size / 1024 / 1024).toFixed(2)} MB · {file.type || "document"}</span></div><button type="button" aria-label="Remove selected file" onClick={() => { setFile(null); setState("idle"); setDocumentId(null); setOcrResult(null); setTamperingResult(null); setOcrState("idle"); setTamperingState("idle"); }}><X size={18} /></button></div>}{state === "uploading" && <p className="upload-status" role="status">Uploading document...</p>}{state === "success" && <div className="upload-success" role="status"><CheckCircle2 size={22} /><div><strong>Document securely uploaded.</strong><span>Status: READY FOR ANALYSIS. Upload success does not mean the document is authentic or verified.</span></div></div>}{state === "error" && <div className="upload-error" role="alert"><strong>Upload failed</strong><span>{message}</span></div>}{state !== "success" && <button type="button" className="button button-primary upload-submit" disabled={!file || state === "uploading"} onClick={() => void upload()}>{state === "uploading" ? "Uploading..." : "Upload document"}</button>}</Card>
    {state === "success" && <Card><div className="console-card-heading"><div><h2>Step 3 · OCR extraction</h2><p>Run server-side OCR on the securely stored document.</p></div><ScanLine size={24} /></div>{ocrState === "idle" && <><p className="placeholder-note">Provider: DEMO / SIMULATED. Only explicitly marked demo fixtures are processed.</p><button type="button" className="button button-primary" onClick={() => void startOCR()}>Start OCR</button></>}{ocrState === "processing" && <p className="upload-status" role="status">OCR PROCESSING · Extracting document text...</p>}{ocrState === "error" && <div className="upload-error" role="alert"><strong>OCR failed</strong><span>{message}</span></div>}{ocrState === "complete" && ocrResult && <div className="ocr-result" role="status"><div className="upload-success"><CheckCircle2 size={22} /><div><strong>OCR COMPLETE</strong><span>Text extracted successfully. Provider: {ocrResult.provider}. Ready for technical analysis.</span></div></div><div className="ocr-summary"><div><span>Confidence</span><strong>{Math.round(ocrResult.overall_confidence * 100)}%</strong></div><div><span>Fields extracted</span><strong>{ocrResult.fields.length}</strong></div><div><span>Language</span><strong>{ocrResult.language}</strong></div></div><h3>Structured fields</h3><div className="ocr-fields">{ocrResult.fields.map((field) => <div className="ocr-field" key={field.name}><span>{field.name.replaceAll("_", " ")}</span><strong>{field.value}</strong><small>Field confidence: {Math.round(field.confidence * 100)}%</small></div>)}</div><details className="ocr-raw"><summary>Show raw OCR text</summary><pre>{ocrResult.raw_text}</pre></details></div>}</Card>}
    {state === "success" && ocrState === "complete" && <Card><div className="console-card-heading"><div><h2>Step 4 · Tampering analysis</h2><p>Technical signal analysis for officer review, not an authenticity decision.</p></div><ScanLine size={24} /></div>{tamperingState === "idle" && <><label className="scenario-label" htmlFor="tampering-scenario">Demo analysis scenario</label><select id="tampering-scenario" className="scenario-select" value={scenario} onChange={(event) => setScenario(event.target.value)}>{scenarios.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><p className="placeholder-note">DEMO MODE · SIMULATED. Fixtures must be explicitly marked; arbitrary uploads are not represented as findings.</p><button type="button" className="button button-primary" onClick={() => void startTampering()}>Start tampering analysis</button></>}{tamperingState === "processing" && <p className="upload-status" role="status">TAMPERING ANALYSIS PROCESSING · Reviewing technical signals...</p>}{tamperingState === "error" && <div className="upload-error" role="alert"><strong>Technical analysis failed</strong><span>{message}</span></div>}{tamperingState === "complete" && tamperingResult && <div className="tampering-result" role="status"><div className="upload-success"><CheckCircle2 size={22} /><div><strong>TECHNICAL ANALYSIS COMPLETE</strong><span>Provider: {tamperingResult.provider}. This result requires officer review and does not prove fraud.</span></div></div><div className="ocr-summary"><div><span>Technical signal score</span><strong>{Math.round(tamperingResult.technical_signal_score * 100)} / 100</strong></div><div><span>Confidence</span><strong>{Math.round(tamperingResult.overall_confidence * 100)}%</strong></div><div><span>Status</span><strong>{tamperingResult.status}</strong></div></div><p className="tampering-summary">{tamperingResult.summary}</p><h3>Findings</h3>{tamperingResult.findings.length === 0 ? <p className="clean-finding">✓ No suspicious alteration signal detected.</p> : <div className="tampering-findings">{tamperingResult.findings.map((finding) => <article className="tampering-finding" key={finding.id}><h4>{finding.title}</h4><p><strong>Severity:</strong> {finding.severity} · <strong>Confidence:</strong> {Math.round(finding.confidence * 100)}%</p><p>{finding.description}</p>{finding.related_ocr_field && <p><strong>Related OCR field:</strong> {finding.related_ocr_field}</p>}<h5>Evidence</h5>{finding.evidence.map((evidence, index) => <div className="evidence-item" key={`${finding.id}-${index}`}><span>{evidence.page ? `Page ${evidence.page} · ` : ""}{evidence.region ?? evidence.evidence_type}</span><small>{evidence.description} · Technical signal: {evidence.technical_signal}</small></div>)}</article>)}</div>}</div>}</Card>}
    {state === "success" && tamperingState === "complete" && <Card><div className="console-card-heading"><div><h2>Step 5 · Face verification</h2><p>Compare a presented photo with the document face through the TrustID API.</p></div><ScanLine size={24} /></div>{faceState === "idle" && <><label className="scenario-label" htmlFor="presented-face">Presented face image · photo-based demo</label><input id="presented-face" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setPresentedFace(event.target.files?.[0] ?? null)} /><label className="scenario-label" htmlFor="face-scenario">Demo comparison scenario</label><select id="face-scenario" className="scenario-select" value={faceScenario} onChange={(event) => setFaceScenario(event.target.value)}>{[["MATCH", "Match"], ["MISMATCH", "Mismatch"], ["REVIEW", "Review"], ["NO_FACE", "No face"], ["MULTIPLE_FACES", "Multiple faces"], ["LOW_QUALITY", "Low quality"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><p className="placeholder-note">DEMO MODE · SIMULATED. Uploaded images are processed server-side and are not retained. This is not liveness detection.</p><button type="button" className="button button-primary" disabled={!presentedFace} onClick={() => void startFaceVerification()}>Compare faces</button></>}{faceState === "preparing" && <p className="upload-status" role="status">Preparing presented face...</p>}{faceState === "comparing" && <p className="upload-status" role="status">Comparing faces...</p>}{faceState === "error" && <div className="upload-error" role="alert"><strong>Face verification failed</strong><span>{message}</span></div>}{faceState === "complete" && faceResult && <div className="face-result" role="status"><div className="upload-success"><CheckCircle2 size={22} /><div><strong>FACE VERIFICATION · {faceResult.outcome}</strong><span>Provider: {faceResult.provider}. This result requires appropriate human review and does not establish legal identity.</span></div></div><div className="ocr-summary"><div><span>Similarity</span><strong>{faceResult.similarity_score == null ? "—" : `${Math.round(faceResult.similarity_score * 100)}%`}</strong></div><div><span>Confidence</span><strong>{faceResult.confidence == null ? "—" : `${Math.round(faceResult.confidence * 100)}%`}</strong></div><div><span>Status</span><strong>{faceResult.status}</strong></div></div><p className="tampering-summary">{faceResult.summary}</p><h3>Evidence</h3><div className="evidence-item">{faceResult.evidence.map((item) => <p key={item.name}><strong>{item.name.replaceAll("_", " ")}:</strong> {item.value} · {item.explanation}</p>)}</div>{faceResult.failure_reason && <p className="upload-error">{faceResult.failure_reason}</p>}</div>}</Card>}
    {state === "success" && faceState === "complete" && <Card><div className="console-card-heading"><div><h2>Step 6 · Verification intelligence</h2><p>Server-side risk assessment from OCR, validation, tampering, and face signals.</p></div><ScanLine size={24} /></div>{analysisState === "idle" && <><p className="placeholder-note">AI-ASSISTED ASSESSMENT · OFFICER DECISION REQUIRED. The prototype score is illustrative and is not an official government rule.</p><button type="button" className="button button-primary" onClick={() => void startAnalysis()}>Analyze this verification</button></>}{analysisState === "processing" && <p className="upload-status" role="status">VERIFICATION ANALYSIS PROCESSING · Calculating explainable factors...</p>}{analysisState === "error" && <div className="upload-error" role="alert"><strong>Analysis unavailable</strong><span>{message}</span></div>}{analysisState === "complete" && analysisResult && <div className="analysis-result" role="status"><div className={`risk-banner risk-${analysisResult.risk.risk_level.toLowerCase()}`}><div><span>Overall assessment</span><strong>{analysisResult.risk.risk_level}</strong></div><div><span>Risk score</span><strong>{analysisResult.risk.risk_score} / 100</strong></div><div><span>Assessment confidence</span><strong>{analysisResult.risk.confidence == null ? "—" : `${Math.round(analysisResult.risk.confidence * 100)}%`}</strong></div></div><p className="tampering-summary"><strong>AI recommendation:</strong> {analysisResult.risk.recommendation}</p><h3>Module results</h3><div className="module-status-grid">{analysisResult.modules.map((module) => <div className="module-status" key={module.name}><strong>{module.name}</strong><span>{module.status}</span><small>{module.summary}</small></div>)}</div><h3>Risk factors</h3><div className="risk-factors">{analysisResult.risk.factors.map((factor) => <article className="risk-factor" key={`${factor.source_module}-${factor.name}`}><div><strong>{factor.name}</strong><span>{factor.severity} · +{factor.contribution}</span></div><small>{factor.explanation}</small><em>Source: {factor.source_module}</em></article>)}</div><div className="officer-decision"><strong>OFFICER DECISION · HUMAN CONTROLLED</strong><span>No decision has been generated by TrustID.</span><div><button type="button" className="button button-secondary">Approve</button><button type="button" className="button button-secondary">Review</button><button type="button" className="button button-secondary">Reject</button></div></div></div>}</Card>}
  </ConsolePage>;
}
