"use client";

import { useEffect, useState } from "react";
import { ClipboardList, Search } from "lucide-react";
import { Card } from "@/components/ui";
import { ConsolePage } from "@/components/console-page";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type AuditItem = { id: string; event_type: string; actor_id: string; verification_id: string; case_id?: string | null; document_id?: string | null; provider?: string | null; status: string; created_at: string }; type AuditResponse = { items: AuditItem[]; total: number; limit: number; offset: number; redaction: string };
export default function AuditPage() { const [eventType, setEventType] = useState(""); const [status, setStatus] = useState(""); const [data, setData] = useState<AuditResponse | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [offset, setOffset] = useState(0); const limit = 25;
  const load = async () => { setState("loading"); try { const params = new URLSearchParams({ limit: String(limit), offset: String(offset) }); if (eventType) params.set("event_type", eventType); if (status) params.set("status", status); const response = await fetch(`${API_URL}/api/v1/audit/events?${params}`, { credentials: "include" }); if (!response.ok) throw new Error(); setData(await response.json() as AuditResponse); setState("ready"); } catch { setState("error"); } };
  useEffect(() => { void load(); }, [offset, eventType, status]); // eslint-disable-line react-hooks/exhaustive-deps
  return <ConsolePage title="Audit Explorer" description="Append-only operational traceability from persisted TrustID audit events."><Card><div className="audit-toolbar"><label><span>Event type</span><div className="case-search"><Search size={16} /><input value={eventType} onChange={(event) => { setOffset(0); setEventType(event.target.value); }} placeholder="CASE_CREATED" /></div></label><label><span>Status</span><input value={status} onChange={(event) => { setOffset(0); setStatus(event.target.value); }} placeholder="COMPLETED" /></label></div><p className="placeholder-note">Sensitive payloads are not stored or displayed. Audit records cannot be edited or deleted from this console.</p></Card>{state === "loading" && <Card><p className="upload-status" role="status">Loading audit events...</p></Card>}{state === "error" && <Card><div className="upload-error" role="alert"><strong>Audit unavailable</strong><span>You may not have audit permission, or the service is unavailable.</span></div></Card>}{state === "ready" && data && <Card><div className="case-table-heading"><div><h2>Operational events</h2><p>{data.total ? `${data.total} matching events` : "No data available for this period."}</p></div><ClipboardList size={24} /></div>{data.items.length > 0 && <div className="case-table-wrap"><table className="case-table"><thead><tr><th>Timestamp</th><th>Event</th><th>Actor</th><th>Related resources</th><th>Status</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td><strong>{item.event_type.replaceAll("_", " ")}</strong><span>{item.provider ?? "Application workflow"}</span></td><td>{item.actor_id}</td><td><span>Verification: {item.verification_id}</span><span>{item.case_id ? `Case: ${item.case_id}` : "No case reference"}</span></td><td><span className="case-pill status-open">{item.status}</span></td></tr>)}</tbody></table></div>}{data.total > limit && <div className="pagination"><button className="button button-secondary" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - limit))}>Previous</button><span>Showing {offset + 1}–{Math.min(offset + limit, data.total)} of {data.total}</span><button className="button button-secondary" disabled={offset + limit >= data.total} onClick={() => setOffset(offset + limit)}>Next</button></div>}</Card>}</ConsolePage>; }
