"use client";

import { useEffect, useState } from "react";
import { FileDown, FileText } from "lucide-react";
import { Card } from "@/components/ui";
import { ConsolePage } from "@/components/console-page";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "";
type Report = { id: string; report_type: string; reference_type: string; reference_id: string; generated_by: string; report_version: string; created_at: string };

export default function ReportsPage() { const [type, setType] = useState("verification"); const [reference, setReference] = useState(""); const [reports, setReports] = useState<Report[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [message, setMessage] = useState("");
  const load = async () => { try { const response = await fetch(`${API_URL}/api/v1/reports/recent`, { credentials: "include" }); if (!response.ok) throw new Error(); setReports(await response.json() as Report[]); setState("ready"); } catch { setState("error"); } };
  useEffect(() => { void load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const generate = async () => { if (!reference.trim()) { setMessage("Enter a verification or case reference."); return; } setMessage("Generating deterministic report from persisted data..."); const endpoint = type === "verification" ? `/api/v1/reports/verification/${reference.trim()}` : `/api/v1/reports/case/${reference.trim()}`; const response = await fetch(`${API_URL}${endpoint}`, { method: "POST", credentials: "include" }); if (!response.ok) { const data = await response.json().catch(() => ({})) as { detail?: string }; setMessage(data.detail ?? "Report could not be generated."); return; } const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `trustid-${type}-report.pdf`; anchor.click(); URL.revokeObjectURL(url); setReference(""); setMessage("Report generated and downloaded securely."); void load(); };
  return <ConsolePage title="Reports" description="Generate deterministic verification and case reports from persisted TrustID records."><div className="analytics-demo-banner"><strong>REPORTING SAFETY</strong><span>Reports summarize AI-assisted signals and human workflow records. They do not independently establish identity, fraud, criminality, immigration eligibility, or legal status.</span></div><Card><div className="report-form"><label>Report type<select value={type} onChange={(event) => setType(event.target.value)}><option value="verification">Verification report</option><option value="case">Investigation / case report</option></select></label><label>Reference UUID<input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Enter an authorized reference" /></label><button type="button" className="button button-primary" onClick={() => void generate()}><FileDown size={16} /> Generate report</button></div>{message && <p className="placeholder-note" role="status">{message}</p>}</Card><Card><div className="case-table-heading"><div><h2>Recent reports</h2><p>Metadata only; report contents are generated on demand.</p></div><FileText size={24} /></div>{state === "loading" && <p className="upload-status" role="status">Loading report history...</p>}{state === "error" && <div className="upload-error" role="alert"><strong>Reports unavailable</strong><span>Check your permission or try again.</span></div>}{state === "ready" && reports.length === 0 && <p className="placeholder-note">No reports generated in your authorized view.</p>}{state === "ready" && reports.length > 0 && <div className="case-table-wrap"><table className="case-table"><thead><tr><th>Report ID</th><th>Type</th><th>Reference</th><th>Generated</th><th>Version</th></tr></thead><tbody>{reports.map((report) => <tr key={report.id}><td>{report.id}</td><td>{report.report_type}</td><td>{report.reference_id}</td><td>{new Date(report.created_at).toLocaleString()}</td><td>{report.report_version}</td></tr>)}</tbody></table></div>}</Card></ConsolePage>; }
