from enum import StrEnum


class VerificationState(StrEnum):
    CREATED = "CREATED"
    UPLOADED = "UPLOADED"
    QUALITY_CHECK = "QUALITY_CHECK"
    OCR_PROCESSING = "OCR_PROCESSING"
    VALIDATING = "VALIDATING"
    TAMPERING_ANALYSIS = "TAMPERING_ANALYSIS"
    FACE_VERIFICATION = "FACE_VERIFICATION"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    CANCELLED = "CANCELLED"


class FaceResult(StrEnum):
    MATCH = "MATCH"
    NO_MATCH = "NO_MATCH"
    COULD_NOT_VERIFY = "COULD_NOT_VERIFY"
    NOT_AVAILABLE = "NOT_AVAILABLE"


class RiskLevel(StrEnum):
    LOW = "LOW"
    REVIEW = "REVIEW"
    HIGH = "HIGH"


class DocumentStatus(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
